### ISSUE TITLE
Concurrency Issue

### ISSUE THREAD

**Issue by arjun-khadka-beyondid** [totpero/DeviceDetector.NET#29]
Code USed:  Startup.cs

           DeviceDetector.SetVersionTruncation(VersionTruncation.VERSION_TRUNCATION_NONE); 

           var userAgent = context.Request.Headers["User-Agent"]; 

            var deviceDetector = new DeviceDetector(userAgent); 

            deviceDetector.Parse(); 

Issue encounter:
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct. 

at System.Collections.Generic.Dictionary`2.FindEntry(TKey key) 

at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key) 

at DeviceDetectorNET.Cache.DictionaryCache.Contains(String id) 

at DeviceDetectorNET.Cache.DictionaryCache.Fetch(String id) 

at DeviceDetectorNET.Parser.ParserAbstract`2.GetRegexes() 

at DeviceDetectorNET.Parser.Client.LibraryParser..ctor() 

at DeviceDetectorNET.Parser.Client.ClientType.get_Library() 

at DeviceDetectorNET.DeviceDetector.AddClientsParser() 

at DeviceDetectorNET.DeviceDetector..ctor(String userAgent)

**Comment by cpkuo** [comment]
I'm getting the same issue, somewhat random. Aside from restarting the process, how can I avoid getting this error? Once its in a corrupt state, it seems only a restart can solve it.

**Comment by schneidenbach** [comment]
Same thing, this bug suddenly appeared today.

**Comment by schneidenbach** [comment]
@cpkuo care to share the code? :)

**Comment by cpkuo** [comment]
So I went into the source code to match up with the stack trace for this exception and realized I was using a dotnet core version package of DeviceDetector.NET that I don't believe exists anymore. Nuget package manager was not notifying me of updating. So I removed it and started using the latest package of DeviceDetector.NET which now supports the latest .net standard. So far, I have not run into this issue.

**Comment by adamhathcock** [comment]
This can still happen:

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
  at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
  at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
  at DeviceDetectorNET.Cache.DictionaryCache.Contains(String id)
  at DeviceDetectorNET.Cache.DictionaryCache.Fetch(String id)
  at DeviceDetectorNET.Parser.ParserAbstract`2.GetRegexes()
  at DeviceDetectorNET.Parser.Client.MediaPlayerParser..ctor()
  at DeviceDetectorNET.Parser.Client.ClientType.get_MediaPlayer()
  at DeviceDetectorNET.DeviceDetector.AddClientsParser()
  at DeviceDetectorNET.DeviceDetector..ctor(String userAgent)
  at

```

I'm now following the advice to cache userAgents and I set `SetVersionTruncation` once statically

**Comment by adamhathcock** [comment]
I did my final fix has having a custom ICache with ConcurrentDictionary instead of just Dictionary
