### ISSUE TITLE
Version string portion was too short or too long. (Parameter 'input')

### ISSUE THREAD

**Issue by agrinei** [totpero/DeviceDetector.NET#31]
I've found the exception above in my error log. I'm using DeviceDetector.NET 4.2.0 with Asp.Net Core 3.1.8

Hopefully the log will be useful:

Header_User-Agent: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3983.280.0.3987.132 Safari/537.36

caller: @C:\Sources\ElmahCore\ElmahCore\Internal$\CallerInfo.cs:10
System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at DeviceDetectorNET.Parser.Client.BrowserParser.BuildEngine(Engine engineData, String browserVersion)
   at DeviceDetectorNET.Parser.Client.BrowserParser.Parse()
   at DeviceDetectorNET.DeviceDetector.ParseClient()
   at DeviceDetectorNET.DeviceDetector.Parse()

**Comment by totpero** [comment]
Hi @agrinei  In last release 4.3.0 is solved this error using `semver`. Thanks 👍
